const fs = require("node:fs");
const path = require("node:path");

function loadLocalEnvironment(rootDir) {
  [".env", ".env.local"].forEach((fileName) => {
    const filePath = path.join(rootDir, fileName);
    if (!fs.existsSync(filePath)) return;

    try {
      process.loadEnvFile(filePath);
    } catch (error) {
      throw new Error(`無法讀取 ${fileName}: ${error.message}`);
    }
  });
}

function getFirebaseClientConfig() {
  return {
    apiKey: process.env.FIREBASE_API_KEY || "",
    authDomain: process.env.FIREBASE_AUTH_DOMAIN || "",
    projectId: process.env.FIREBASE_PROJECT_ID || "",
    storageBucket: process.env.FIREBASE_STORAGE_BUCKET || "",
    messagingSenderId: process.env.FIREBASE_MESSAGING_SENDER_ID || "",
    appId: process.env.FIREBASE_APP_ID || "",
    adminUid: process.env.FIREBASE_ADMIN_UID || "",
  };
}

function hasCompleteFirebaseConfig(config) {
  return [
    config.apiKey,
    config.authDomain,
    config.projectId,
    config.storageBucket,
    config.messagingSenderId,
    config.appId,
  ].every(Boolean);
}

function writeFirebaseClientConfig(distDir) {
  const config = getFirebaseClientConfig();
  const serializedConfig = JSON.stringify(config, null, 2).replaceAll("<", "\\u003c");
  const contents = `// Generated by scripts/build-posts.js. Do not edit this file.\nwindow.__FIREBASE_CONFIG__ = Object.freeze(${serializedConfig});\n`;
  fs.writeFileSync(path.join(distDir, "firebase-config.js"), contents);
  return config;
}

module.exports = {
  getFirebaseClientConfig,
  hasCompleteFirebaseConfig,
  loadLocalEnvironment,
  writeFirebaseClientConfig,
};
